import argparse
import asyncio
import json
import os
import re
import subprocess
import sys
import time
import traceback

from hoa_projection import project_hoa_file


DEFAULT_VARANUS_HOST = "127.0.0.1"
DEFAULT_VARANUS_PORT = 5087
SHOW_PIPELINE_LOGS = False
GATEWAY_ID = "predictive-monitor"
LABEL_BLOCK_PATTERN = re.compile(r"\[([^\]]*)\]")
SPOT_ERROR_LINE_PATTERN = re.compile(r"([^:\n]+):(\d+)\.(\d+)-(\d+):")


def log_pipeline(message):
    if SHOW_PIPELINE_LOGS:
        print("[PIPELINE] " + str(message), flush=True)


def ensure_log_dir():
    os.makedirs("log", exist_ok=True)


def shorten(text, max_len=220):
    text = str(text)
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def find_generated_hoa():
    """Find the HOA generated by Varanus."""
    preferred_names = ["automaton.hoa", "buchi_automaton.hoa"]
    for candidate in preferred_names:
        if os.path.exists(candidate):
            return candidate

    hoa_candidates = [
        filename for filename in os.listdir(".")
        if filename.endswith(".hoa") and os.path.isfile(filename)
    ]
    if hoa_candidates:
        return max(hoa_candidates, key=os.path.getmtime)

    raise FileNotFoundError("No HOA file found after running Varanus.")


def parse_hoa_metadata(hoa_path):
    metadata = {
        "path": hoa_path,
        "states": None,
        "start": None,
        "properties": None,
        "aps": [],
    }
    with open(hoa_path, "r", encoding="utf-8") as source:
        for line in source:
            stripped = line.strip()
            if stripped.startswith("States:"):
                metadata["states"] = stripped.split(":", 1)[1].strip()
            elif stripped.startswith("Start:"):
                metadata["start"] = stripped.split(":", 1)[1].strip()
            elif stripped.startswith("properties:"):
                metadata["properties"] = stripped[len("properties:"):].strip()
            elif stripped.startswith("AP:"):
                metadata["aps"] = re.findall(r'"([^"]*)"', stripped)
            elif stripped == "--BODY--":
                break
    return metadata


def log_hoa_metadata(label, metadata, debug=False):
    log_pipeline(
        "{label}: path={path} states={states} start={start} ap_count={ap_count} properties='{props}'".format(
            label=label,
            path=metadata["path"],
            states=metadata["states"],
            start=metadata["start"],
            ap_count=len(metadata["aps"]),
            props=metadata["properties"],
        )
    )
    if debug:
        log_pipeline("{label} AP list: {aps}".format(label=label, aps=", ".join(metadata["aps"])))


def _read_text_lines(path):
    try:
        with open(path, "r", encoding="utf-8") as source:
            return source.read().splitlines()
    except OSError:
        return []


def _extract_spot_error_line_numbers(error_text, hoa_path):
    wanted_name = os.path.basename(hoa_path)
    line_numbers = []
    for match in SPOT_ERROR_LINE_PATTERN.finditer(str(error_text)):
        ref_path = match.group(1)
        if os.path.basename(ref_path) == wanted_name:
            line_numbers.append(int(match.group(2)))
    return sorted(set(line_numbers))


def _find_identifier_label_lines(lines, max_items=12):
    """Find label lines that still include identifiers (helpful for Spot parse failures)."""
    items = []
    for idx, line in enumerate(lines, start=1):
        label_match = LABEL_BLOCK_PATTERN.search(line)
        if not label_match:
            continue
        formula = label_match.group(1)
        # Ignore numeric-only formulas/operators; surface textual tokens.
        identifier_tokens = re.findall(r"[A-Za-z_][A-Za-z0-9_.]*", formula)
        filtered = [tok for tok in identifier_tokens if tok.lower() not in {"t", "f", "true", "false"}]
        if filtered:
            items.append((idx, line.rstrip("\n"), filtered))
            if len(items) >= max_items:
                break
    return items


def print_hoa_parse_diagnostics(error, hoa_path):
    print("[DIAG] Spot failed to parse projected HOA: {path}".format(path=os.path.abspath(hoa_path)), flush=True)
    print("[DIAG] Spot error: {msg}".format(msg=str(error)), flush=True)

    lines = _read_text_lines(hoa_path)
    if not lines:
        print("[DIAG] Could not read HOA file for context.", flush=True)
        return

    ap_line = next((line for line in lines if line.startswith("AP:")), None)
    if ap_line is not None:
        print("[DIAG] {line}".format(line=ap_line), flush=True)

    line_numbers = _extract_spot_error_line_numbers(str(error), hoa_path)
    if line_numbers:
        print("[DIAG] Context around reported HOA lines:", flush=True)
        seen = set()
        for center in line_numbers:
            for ln in range(max(1, center - 2), min(len(lines), center + 2) + 1):
                if ln in seen:
                    continue
                seen.add(ln)
                marker = ">>" if ln == center else "  "
                print("[DIAG] {marker} {ln:6d}: {text}".format(
                    marker=marker,
                    ln=ln,
                    text=lines[ln - 1],
                ), flush=True)
    else:
        print("[DIAG] Spot error did not include parse line numbers.", flush=True)

    suspect_labels = _find_identifier_label_lines(lines)
    if suspect_labels:
        print("[DIAG] Labels still containing identifiers (first {count}):".format(count=len(suspect_labels)), flush=True)
        for ln, text, tokens in suspect_labels:
            print("[DIAG]   line {ln}: tokens={tokens} :: {text}".format(
                ln=ln,
                tokens=",".join(tokens),
                text=text,
            ), flush=True)


def preflight_predictive_runtime(projected_hoa_path, projected_ltl_formula, verbose=False):
    spot, _, PredictiveRuntime, _ = import_predictive_runtime_dependencies()
    try:
        model = spot.automaton(projected_hoa_path)
        PredictiveRuntime(projected_ltl_formula, model)
        if verbose:
            print(
                "[DIAG] preflight ok: projected_hoa={hoa} formula='{formula}'".format(
                    hoa=os.path.abspath(projected_hoa_path),
                    formula=projected_ltl_formula,
                ),
                flush=True,
            )
    except SyntaxError as error:
        print_hoa_parse_diagnostics(error, projected_hoa_path)
        raise
    except Exception as error:
        print("[DIAG] Predictive runtime preflight failed: {etype}: {msg}".format(
            etype=error.__class__.__name__,
            msg=error,
        ), flush=True)
        raise


def run_varanus_buchi(config_file, varanus_script, varanus_python, verbose_varanus=False):
    """Run Varanus to generate a Buchi automaton HOA."""
    command = [varanus_python, varanus_script, "buchi-automaton", config_file]
    log_path = os.path.join("log", "varanus_buchi.log")
    try:
        if verbose_varanus:
            subprocess.run(command, check=True)
        else:
            ensure_log_dir()
            with open(log_path, "w", encoding="utf-8") as log_file:
                subprocess.run(
                    command,
                    check=True,
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                )
            log_pipeline("varanus buchi log: {path}".format(path=log_path))
    except FileNotFoundError as error:
        print(
            "Error while running Varanus: could not execute '{cmd}'. "
            "Check --varanus-python and --varanus-script.".format(cmd=error.filename)
        )
        sys.exit(1)
    except subprocess.CalledProcessError as error:
        print(f"Error while running varanus: {error}")
        if not verbose_varanus:
            print("See Varanus build output in: {path}".format(path=log_path))
        print(
            "Hint: if this is an FDR import error (PyInit__fdr), run Varanus with the "
            "Python version matching FDR via --varanus-python (often python3.8)."
        )
        sys.exit(1)


def start_varanus_online(config_file, varanus_script, varanus_python, verbose_varanus=False):
    """Start standalone Varanus in online mode."""
    command = [varanus_python, varanus_script, "online", config_file]
    log_path = os.path.join("log", "varanus_online.log")
    try:
        if verbose_varanus:
            process = subprocess.Popen(command)
            process._varanus_log_file = None
            return process

        ensure_log_dir()
        log_file = open(log_path, "w", encoding="utf-8")
        process = subprocess.Popen(
            command,
            stdout=log_file,
            stderr=subprocess.STDOUT,
        )
        process._varanus_log_file = log_file
        process._varanus_log_path = log_path
        log_pipeline("varanus online log: {path}".format(path=log_path))
        return process
    except FileNotFoundError as error:
        print(
            "Error while starting Varanus online monitor: could not execute '{cmd}'. "
            "Check --varanus-python and --varanus-script.".format(cmd=error.filename)
        )
        sys.exit(1)
    except OSError as error:
        print(f"Error while starting Varanus online monitor: {error}")
        sys.exit(1)


def stop_varanus_online(process):
    if process is None:
        return
    try:
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=5)
    finally:
        log_file = getattr(process, "_varanus_log_file", None)
        if log_file is not None and not log_file.closed:
            log_file.close()


def normalize_ws_message(message):
    if isinstance(message, bytes):
        return message.decode("utf-8", errors="replace")
    return str(message)


def is_websocket_closed_error(error):
    return error.__class__.__name__.startswith("ConnectionClosed")


def project_ltl_formula(formula, projection_map):
    projected_formula = str(formula)
    # Longest keys first avoids partial replacements when AP names share prefixes.
    for ap_name in sorted(projection_map.keys(), key=len, reverse=True):
        pattern = r"(?<![A-Za-z0-9_])" + re.escape(ap_name) + r"(?![A-Za-z0-9_])"
        projected_formula = re.sub(pattern, projection_map[ap_name], projected_formula)
    return projected_formula


def resolve_projected_event(parsed_event, projection_map, projected_symbols):
    if parsed_event in projection_map:
        return projection_map[parsed_event]
    if parsed_event in projected_symbols:
        return parsed_event
    raise ValueError(
        f"Transformed Varanus event '{parsed_event}' is not in projected HOA AP map."
    )


def normalize_gate_verdict(verdict):
    normalized = str(verdict).strip().lower()
    if normalized in {"currently_true", "true"}:
        return "currently_true"
    if normalized in {"false", "currently_false"}:
        return "false"
    if normalized in {"ignored", "ignore"}:
        return "ignored"
    return normalized


def extract_parsed_event(gate_reply):
    parsed_event = gate_reply.get("parsed_event")
    if parsed_event is None:
        parsed_event = gate_reply.get("event")
    if parsed_event in (None, ""):
        return None
    return parsed_event


async def connect_varanus_ws(websockets, varanus_url, retries=20, delay_seconds=0.25):
    last_error = None
    for _ in range(retries):
        try:
            try:
                return await websockets.connect(
                    varanus_url,
                    compression=None,
                    ping_interval=None,
                )
            except TypeError:
                return await websockets.connect(varanus_url)
        except Exception as error:  # pragma: no cover
            last_error = error
            await asyncio.sleep(delay_seconds)
    raise RuntimeError(f"Could not connect to Varanus websocket at {varanus_url}: {last_error}")


async def gate_with_varanus(varanus_ws, raw_message):
    await varanus_ws.send(raw_message)
    reply_message = normalize_ws_message(await varanus_ws.recv())

    try:
        payload = json.loads(reply_message)
        if isinstance(payload, dict):
            return payload
        return {"verdict": "error", "raw_reply": payload}
    except json.JSONDecodeError:
        return {"verdict": "error", "raw_reply": reply_message}


def with_legacy_top_level_fields(payload, gate_reply):
    """Keep backward-compatible top-level fields expected by legacy ROS clients."""
    response = dict(payload)
    if not isinstance(gate_reply, dict):
        return response

    for key in ("topic", "time", "value", "header", "pose", "type", "parsed_event"):
        if key in gate_reply and key not in response:
            response[key] = gate_reply.get(key)

    if "event" not in response and "parsed_event" in gate_reply:
        response["event"] = gate_reply.get("parsed_event")
    if "varanus_verdict" not in response and "verdict" in gate_reply:
        response["varanus_verdict"] = gate_reply.get("verdict")
    if "varanus" not in response:
        response["varanus"] = gate_reply
    return response


def format_event_overview(raw_message, gate_reply):
    topic = gate_reply.get("topic", "?")
    parsed = gate_reply.get("parsed_event", "-")

    value = gate_reply.get("value")
    location = gate_reply.get("location")
    name = gate_reply.get("name")

    details = []
    if name is not None:
        details.append("name={name}".format(name=name))
    if location is not None:
        details.append("location={location}".format(location=location))
    if value is not None:
        details.append("value={value}".format(value=value))

    if not details:
        raw_json = None
        try:
            raw_json = json.loads(raw_message)
        except Exception:
            raw_json = None
        if isinstance(raw_json, dict):
            for key in ("name", "location", "value"):
                if key in raw_json:
                    details.append("{key}={value}".format(key=key, value=raw_json[key]))

    suffix = (" " + " ".join(details)) if details else ""
    return "topic={topic} parsed={parsed}{suffix}".format(
        topic=topic,
        parsed=parsed,
        suffix=suffix,
    )


def print_event_summary(index, overview, gate_verdict, ltl_text, final_verdict, decision_source, reason=None):
    reason_suffix = ""
    if reason:
        reason_suffix = " reason={reason}".format(reason=reason)
    print(
        "[EVENT {idx}] {overview} varanus={varanus} ltl={ltl} final={final} source={source}{reason}".format(
            idx=index,
            overview=overview,
            varanus=gate_verdict,
            ltl=ltl_text,
            final=final_verdict,
            source=decision_source,
            reason=reason_suffix,
        ),
        flush=True,
    )


def import_predictive_runtime_dependencies():
    try:
        import spot
        import websockets
        from predictive_ltl import PredictiveRuntime, Verdict
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "Missing Python dependency for monitor online/offline pipeline. "
            "Run monitor.py with a Python that has spot/buddy/websockets installed."
        ) from error

    return spot, websockets, PredictiveRuntime, Verdict


async def run_offline_pipeline(
    ltl_formula,
    projected_hoa_path,
    projection_map,
    trace_path,
    varanus_host,
    varanus_port,
    debug=False,
):
    spot, websockets, PredictiveRuntime, Verdict = import_predictive_runtime_dependencies()

    runtime = PredictiveRuntime(ltl_formula, spot.automaton(projected_hoa_path))
    projected_symbols = set(projection_map.values())
    varanus_url = f"ws://{varanus_host}:{varanus_port}"

    start_time = time.time()
    processed_events = 0
    warned_varanus_internal_predictive = False

    varanus_ws = await connect_varanus_ws(websockets, varanus_url)
    try:
        with open(trace_path, "r", encoding="utf-8") as source:
            for line_number, raw_line in enumerate(source, start=1):
                raw_event = raw_line.rstrip("\n")
                if raw_event == "":
                    continue

                processed_events += 1
                gate_reply = await gate_with_varanus(varanus_ws, raw_event)
                if (not warned_varanus_internal_predictive) and isinstance(gate_reply, dict) and (
                    "predictive_verdict" in gate_reply or "predictive_reason" in gate_reply
                ):
                    print(
                        "[WARN] Varanus reply already contains predictive fields. "
                        "This suggests Varanus internal predictive_ltl_ws_url is enabled. "
                        "For this architecture, disable it and let PredictiveVaranus decide predictive verdicts.",
                        flush=True,
                    )
                    warned_varanus_internal_predictive = True
                gate_verdict = normalize_gate_verdict(gate_reply.get("verdict", ""))
                overview = format_event_overview(raw_event, gate_reply)
                if debug:
                    log_pipeline(
                        "offline raw event #{idx}: {raw}".format(
                            idx=processed_events,
                            raw=shorten(raw_event),
                        )
                    )

                if gate_verdict == "false":
                    print_event_summary(
                        processed_events,
                        overview,
                        gate_verdict,
                        "-",
                        "false",
                        "varanus",
                        reason="varanus_rejected",
                    )
                    elapsed = time.time() - start_time
                    print(f"RES: FALSE;source=varanus;line={line_number};events={processed_events};time={elapsed}")
                    return

                if gate_verdict != "currently_true":
                    print_event_summary(
                        processed_events,
                        overview,
                        gate_verdict,
                        "-",
                        gate_verdict,
                        "varanus",
                        reason="varanus_non_accepting",
                    )
                    continue

                parsed_event = extract_parsed_event(gate_reply)
                if parsed_event is None:
                    if debug:
                        log_pipeline(
                            "offline missing parsed event: keys={keys} reply={reply}".format(
                                keys=sorted(gate_reply.keys()) if isinstance(gate_reply, dict) else type(gate_reply),
                                reply=shorten(json.dumps(gate_reply, sort_keys=True) if isinstance(gate_reply, dict) else gate_reply, 420),
                            )
                        )
                    print_event_summary(
                        processed_events,
                        overview,
                        gate_verdict,
                        "-",
                        gate_verdict,
                        "varanus",
                        reason="missing_parsed_event",
                    )
                    continue

                projected_event = resolve_projected_event(
                    parsed_event,
                    projection_map,
                    projected_symbols,
                )

                predictive_verdict = runtime.step(projected_event)
                step_info = runtime.get_last_step_info()
                predictive_reason = step_info.get("reason", "unknown")
                if debug:
                    log_pipeline(
                        "offline predictive detail: event='{event}' reason={reason} info={info}".format(
                            event=projected_event,
                            reason=predictive_reason,
                            info=json.dumps(step_info, sort_keys=True),
                        )
                    )
                if predictive_verdict == Verdict.tt:
                    predictive_text = "true"
                    final_text = "true"
                    source_text = "ltl"
                elif predictive_verdict == Verdict.ff:
                    predictive_text = "false"
                    final_text = "false"
                    source_text = "ltl"
                else:
                    predictive_text = "?"
                    final_text = "currently_true"
                    source_text = "varanus"
                print_event_summary(
                    processed_events,
                    overview,
                    gate_verdict,
                    predictive_text,
                    final_text,
                    source_text,
                    reason=predictive_reason,
                )
                if predictive_verdict == Verdict.tt:
                    elapsed = time.time() - start_time
                    print(
                        "RES: TRUE;source=predictive;reason={reason};line={line};events={events};time={time}".format(
                            reason=predictive_reason,
                            line=line_number,
                            events=processed_events,
                            time=elapsed,
                        )
                    )
                    return
                if predictive_verdict == Verdict.ff:
                    elapsed = time.time() - start_time
                    print(
                        "RES: FALSE;source=predictive;reason={reason};line={line};events={events};time={time}".format(
                            reason=predictive_reason,
                            line=line_number,
                            events=processed_events,
                            time=elapsed,
                        )
                    )
                    return
    finally:
        await varanus_ws.close()

    elapsed = time.time() - start_time
    print(f"RES: ?;source=predictive;events={processed_events};time={elapsed}")


async def run_online_pipeline(
    ltl_formula,
    projected_hoa_path,
    projection_map,
    host,
    port,
    varanus_host,
    varanus_port,
    debug=False,
):
    spot, websockets, PredictiveRuntime, Verdict = import_predictive_runtime_dependencies()
    projected_symbols = set(projection_map.values())
    varanus_url = f"ws://{varanus_host}:{varanus_port}"
    active_clients = set()
    counters = {"events": 0}
    runtime_init_error_reported = False
    warned_varanus_internal_predictive = False

    async def handler(client_ws, path=None):
        nonlocal runtime_init_error_reported
        nonlocal warned_varanus_internal_predictive

        try:
            runtime = PredictiveRuntime(ltl_formula, spot.automaton(projected_hoa_path))
        except SyntaxError as error:
            print("[CLIENT] runtime init failed due to HOA parse error", flush=True)
            if not runtime_init_error_reported:
                print_hoa_parse_diagnostics(error, projected_hoa_path)
                runtime_init_error_reported = True
            try:
                await client_ws.send(json.dumps({
                    "status": "error",
                    "gateway_id": GATEWAY_ID,
                    "error": "predictive_runtime_init_failed",
                    "detail": str(error),
                }))
            except Exception:
                pass
            await client_ws.close()
            return
        except Exception as error:
            print(
                "[CLIENT] runtime init failed: {etype}: {msg}".format(
                    etype=error.__class__.__name__,
                    msg=error,
                ),
                flush=True,
            )
            try:
                await client_ws.send(json.dumps({
                    "status": "error",
                    "gateway_id": GATEWAY_ID,
                    "error": "predictive_runtime_init_failed",
                    "detail": str(error),
                }))
            except Exception:
                pass
            await client_ws.close()
            return
        remote_addr = getattr(client_ws, "remote_address", None)
        active_clients.add(str(remote_addr))
        log_pipeline("client connected: {addr}".format(addr=remote_addr))
        print("[CLIENT] connected: {addr}".format(addr=remote_addr), flush=True)
        event_index = 0

        varanus_ws = await connect_varanus_ws(websockets, varanus_url)
        try:
            try:
                async for incoming in client_ws:
                    raw_message = normalize_ws_message(incoming)
                    if raw_message.strip() == "":
                        await client_ws.send(json.dumps({"status": "ignored", "reason": "empty message"}))
                        continue

                    try:
                        event_index += 1
                        counters["events"] += 1
                        print(
                            "[EVENT {idx}] observed raw={raw}".format(
                                idx=event_index,
                                raw=shorten(raw_message, 260),
                            ),
                            flush=True,
                        )
                        gate_reply = await gate_with_varanus(varanus_ws, raw_message)
                        if (not warned_varanus_internal_predictive) and isinstance(gate_reply, dict) and (
                            "predictive_verdict" in gate_reply or "predictive_reason" in gate_reply
                        ):
                            print(
                                "[WARN] Varanus reply already contains predictive fields. "
                                "This suggests Varanus internal predictive_ltl_ws_url is enabled. "
                                "For this architecture, disable it and let PredictiveVaranus decide predictive verdicts.",
                                flush=True,
                            )
                            warned_varanus_internal_predictive = True
                        gate_verdict = normalize_gate_verdict(gate_reply.get("verdict", ""))
                        overview = format_event_overview(raw_message, gate_reply)
                        if debug:
                            log_pipeline(
                                "online raw event #{idx}: {raw}".format(
                                    idx=event_index,
                                    raw=shorten(raw_message),
                                )
                            )

                        if gate_verdict != "currently_true":
                            print_event_summary(
                                event_index,
                                overview,
                                gate_verdict,
                                "-",
                                gate_reply.get("verdict", "false"),
                                "varanus",
                                reason="varanus_rejected_or_ignored",
                            )
                            response = with_legacy_top_level_fields({
                                "status": "blocked",
                                "gateway_id": GATEWAY_ID,
                                "verdict": gate_verdict or str(gate_reply.get("verdict", "false")),
                                "ltl_verdict": "-",
                                "decision_source": "varanus",
                                "reason": "varanus_rejected_or_ignored",
                                "varanus": gate_reply,
                            }, gate_reply)
                            log_pipeline(
                                "decision source=varanus verdict={verdict}".format(
                                    verdict=response["verdict"]
                                )
                            )
                            await client_ws.send(json.dumps(response))
                            continue

                        parsed_event = extract_parsed_event(gate_reply)
                        if parsed_event is None:
                            if debug:
                                log_pipeline(
                                    "online missing parsed event: keys={keys} reply={reply}".format(
                                        keys=sorted(gate_reply.keys()) if isinstance(gate_reply, dict) else type(gate_reply),
                                        reply=shorten(json.dumps(gate_reply, sort_keys=True) if isinstance(gate_reply, dict) else gate_reply, 420),
                                    )
                                )
                            print_event_summary(
                                event_index,
                                overview,
                                gate_verdict,
                                "-",
                                gate_verdict or str(gate_reply.get("verdict", "false")),
                                "varanus",
                                reason="missing_parsed_event",
                            )
                            response = with_legacy_top_level_fields({
                                "status": "blocked",
                                "gateway_id": GATEWAY_ID,
                                "verdict": gate_verdict or str(gate_reply.get("verdict", "false")),
                                "ltl_verdict": "-",
                                "decision_source": "varanus",
                                "reason": "missing_parsed_event",
                                "varanus": gate_reply,
                            }, gate_reply)
                            log_pipeline(
                                "decision source=varanus verdict={verdict} reason=missing_parsed_event".format(
                                    verdict=response["verdict"]
                                )
                            )
                            await client_ws.send(json.dumps(response))
                            continue

                        projected_event = resolve_projected_event(
                            parsed_event,
                            projection_map,
                            projected_symbols,
                        )
                        predictive_verdict = runtime.step(projected_event)
                        step_info = runtime.get_last_step_info()
                        predictive_reason = step_info.get("reason", "unknown")

                        if predictive_verdict == Verdict.tt:
                            predictive_text = "true"
                        elif predictive_verdict == Verdict.ff:
                            predictive_text = "false"
                        else:
                            predictive_text = "?"

                        if predictive_text == "?":
                            final_verdict = "currently_true"
                            decision_source = "varanus"
                        else:
                            final_verdict = predictive_text
                            decision_source = "ltl"

                        print_event_summary(
                            event_index,
                            overview,
                            gate_verdict,
                            predictive_text,
                            final_verdict,
                            decision_source,
                            reason=predictive_reason,
                        )
                        if debug:
                            log_pipeline(
                                "online predictive detail: {info}".format(
                                    info=json.dumps(step_info, sort_keys=True)
                                )
                            )

                        response = with_legacy_top_level_fields({
                            "status": "ok",
                            "gateway_id": GATEWAY_ID,
                            "verdict": final_verdict,
                            "decision_source": decision_source,
                            "varanus": gate_reply,
                            "projected_event": projected_event,
                            "predictive_verdict": predictive_text,
                            "ltl_verdict": predictive_text,
                            "predictive_reason": predictive_reason,
                        }, gate_reply)
                        if debug:
                            response["predictive_debug"] = step_info
                        await client_ws.send(json.dumps(response))
                    except Exception as error:
                        print(
                            "[EVENT {idx}] ERROR type={etype} message={msg}".format(
                                idx=event_index,
                                etype=error.__class__.__name__,
                                msg=shorten(str(error), 320),
                            ),
                            flush=True,
                        )
                        if debug:
                            traceback.print_exc()
                        if is_websocket_closed_error(error):
                            break
                        try:
                            await client_ws.send(json.dumps({"status": "error", "error": str(error)}))
                        except Exception:
                            break
            except Exception as error:
                if not is_websocket_closed_error(error):
                    raise
        finally:
            await varanus_ws.close()
            active_clients.discard(str(remote_addr))
            log_pipeline("client disconnected: {addr}".format(addr=remote_addr))
            print("[CLIENT] disconnected: {addr}".format(addr=remote_addr), flush=True)

    print(f"Online predictive monitor listening on ws://{host}:{port}")
    print(f"Varanus gate expected at ws://{varanus_host}:{varanus_port}")
    print("Waiting for events. Each event will print as: [EVENT N] ...")
    async with websockets.serve(handler, host, port):
        await asyncio.Future()


def main():
    global SHOW_PIPELINE_LOGS
    global GATEWAY_ID

    parser = argparse.ArgumentParser(
        description="Monitor script for Varanus-first predictive LTL.",
        allow_abbrev=False,
    )
    parser.add_argument("config", help="Path to the Varanus config.yaml file.", type=str)
    parser.add_argument("ltl", help="LTL formula to verify.", type=str)
    parser.add_argument("trace", nargs="?", help="Path to trace file (offline mode).", type=str)

    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument("--offline", action="store_true", help="Run offline mode with trace replay.")
    mode_group.add_argument("--online", action="store_true", help="Run online websocket mode.")

    parser.add_argument("--host", default="127.0.0.1", help="Predictive websocket host (online mode).")
    parser.add_argument("--port", type=int, default=5088, help="Predictive websocket port (online mode).")

    parser.add_argument("--varanus-script", default="varanus.py", help="Path to varanus.py.")
    parser.add_argument("--varanus-python", default="python3", help="Python executable for Varanus.")
    parser.add_argument("--varanus-host", default=DEFAULT_VARANUS_HOST, help="Varanus websocket host.")
    parser.add_argument("--varanus-port", type=int, default=DEFAULT_VARANUS_PORT, help="Varanus websocket port.")
    parser.add_argument(
        "--verbose-varanus",
        action="store_true",
        help="Show full Varanus stdout/stderr on terminal (otherwise redirected to log/*.log).",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose diagnostics (implies --debug and --verbose-varanus).",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Print detailed diagnostics (HOA metadata, AP mapping, and predictive step reasons).",
    )
    args = parser.parse_args()
    if args.verbose:
        args.debug = True
        args.verbose_varanus = True

    SHOW_PIPELINE_LOGS = bool(args.debug)
    GATEWAY_ID = "pm-{pid}-{ts}".format(pid=os.getpid(), ts=int(time.time()))

    offline_mode = args.offline or not args.online

    if offline_mode and not args.trace:
        parser.error("trace is required in offline mode.")
    if args.online and args.port == args.varanus_port and args.host == args.varanus_host:
        parser.error("Predictive websocket host/port must differ from Varanus websocket host/port.")

    # 1) Build Varanus Buchi and project APs.
    run_varanus_buchi(
        args.config,
        args.varanus_script,
        args.varanus_python,
        verbose_varanus=args.verbose_varanus,
    )

    generated_hoa = find_generated_hoa()
    generated_hoa_metadata = parse_hoa_metadata(generated_hoa)
    try:
        projected_hoa, projection_map = project_hoa_file(
            input_hoa_path=generated_hoa,
            output_hoa_path="automaton_projected.hoa",
            mapping_output_path="event_projection_map.json",
            prefix="p",
        )
    except (FileNotFoundError, ValueError) as error:
        print(f"Error while projecting HOA: {error}")
        sys.exit(1)

    projected_hoa_metadata = parse_hoa_metadata(projected_hoa)

    projected_ltl_formula = project_ltl_formula(args.ltl, projection_map)
    log_hoa_metadata("hoa source", generated_hoa_metadata, debug=args.debug)
    log_hoa_metadata("hoa projected", projected_hoa_metadata, debug=args.debug)
    log_pipeline(
        "projection map: entries={count} file={path}".format(
            count=len(projection_map),
            path="event_projection_map.json",
        )
    )
    if args.debug:
        for source_ap, projected_ap in sorted(projection_map.items()):
            log_pipeline("projection: {src} -> {dst}".format(src=source_ap, dst=projected_ap))

    log_pipeline("ltl formula input: {f}".format(f=args.ltl))
    log_pipeline("ltl formula projected: {f}".format(f=projected_ltl_formula))
    if args.verbose:
        print(
            "[DIAG] startup: cwd={cwd} host={host}:{port} varanus_gate={vhost}:{vport} gateway_id={gid}".format(
                cwd=os.getcwd(),
                host=args.host,
                port=args.port,
                vhost=args.varanus_host,
                vport=args.varanus_port,
                gid=GATEWAY_ID,
            ),
            flush=True,
        )
        print(
            "[DIAG] files: source_hoa={src} projected_hoa={dst} projection_map={mapf}".format(
                src=os.path.abspath(generated_hoa),
                dst=os.path.abspath(projected_hoa),
                mapf=os.path.abspath("event_projection_map.json"),
            ),
            flush=True,
        )

    try:
        preflight_predictive_runtime(
            projected_hoa_path=projected_hoa,
            projected_ltl_formula=projected_ltl_formula,
            verbose=args.verbose,
        )
    except Exception:
        print("Monitor stopped due to predictive runtime preflight failure.", flush=True)
        sys.exit(1)

    # 2) Start Varanus online gate for both modes.
    varanus_process = start_varanus_online(
        args.config,
        args.varanus_script,
        args.varanus_python,
        verbose_varanus=args.verbose_varanus,
    )
    print(
        "Standalone Varanus gate started "
        f"(pid={varanus_process.pid}) on ws://{args.varanus_host}:{args.varanus_port}"
    )
    print("Gateway id: {gid}".format(gid=GATEWAY_ID))

    try:
        if offline_mode:
            asyncio.run(
                run_offline_pipeline(
                    projected_ltl_formula,
                    projected_hoa,
                    projection_map,
                    args.trace,
                    args.varanus_host,
                    args.varanus_port,
                    args.debug,
                )
            )
        else:
            asyncio.run(
                run_online_pipeline(
                    projected_ltl_formula,
                    projected_hoa,
                    projection_map,
                    args.host,
                    args.port,
                    args.varanus_host,
                    args.varanus_port,
                    args.debug,
                )
            )
    except KeyboardInterrupt:
        print("Monitor stopped.")
    finally:
        stop_varanus_online(varanus_process)


if __name__ == "__main__":
    main()
