import argparse
import asyncio
import json
import os
import re
import subprocess
import sys
import time

from hoa_projection import project_hoa_file


DEFAULT_VARANUS_HOST = "127.0.0.1"
DEFAULT_VARANUS_PORT = 5087


def log_pipeline(message):
    print("[PIPELINE] " + str(message), flush=True)


def find_generated_hoa():
    """Find the HOA generated by Varanus."""
    preferred_names = ["automaton.hoa", "buchi_automaton.hoa"]
    for candidate in preferred_names:
        if os.path.exists(candidate):
            return candidate

    hoa_candidates = [
        filename for filename in os.listdir(".")
        if filename.endswith(".hoa") and os.path.isfile(filename)
    ]
    if hoa_candidates:
        return max(hoa_candidates, key=os.path.getmtime)

    raise FileNotFoundError("No HOA file found after running Varanus.")


def run_varanus_buchi(config_file, varanus_script, varanus_python):
    """Run Varanus to generate a Buchi automaton HOA."""
    command = [varanus_python, varanus_script, "buchi-automaton", config_file]
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as error:
        print(f"Error while running varanus: {error}")
        print(
            "Hint: if this is an FDR import error (PyInit__fdr), run Varanus with the "
            "Python version matching FDR via --varanus-python (often python3.8)."
        )
        sys.exit(1)


def start_varanus_online(config_file, varanus_script, varanus_python):
    """Start standalone Varanus in online mode."""
    command = [varanus_python, varanus_script, "online", config_file]
    try:
        return subprocess.Popen(command)
    except OSError as error:
        print(f"Error while starting Varanus online monitor: {error}")
        sys.exit(1)


def stop_varanus_online(process):
    if process is None:
        return
    if process.poll() is not None:
        return

    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5)


def normalize_ws_message(message):
    if isinstance(message, bytes):
        return message.decode("utf-8", errors="replace")
    return str(message)


def is_websocket_closed_error(error):
    return error.__class__.__name__.startswith("ConnectionClosed")


def project_ltl_formula(formula, projection_map):
    projected_formula = str(formula)
    # Longest keys first avoids partial replacements when AP names share prefixes.
    for ap_name in sorted(projection_map.keys(), key=len, reverse=True):
        pattern = r"(?<![A-Za-z0-9_])" + re.escape(ap_name) + r"(?![A-Za-z0-9_])"
        projected_formula = re.sub(pattern, projection_map[ap_name], projected_formula)
    return projected_formula


def resolve_projected_event(parsed_event, projection_map, projected_symbols):
    if parsed_event in projection_map:
        return projection_map[parsed_event]
    if parsed_event in projected_symbols:
        return parsed_event
    raise ValueError(
        f"Transformed Varanus event '{parsed_event}' is not in projected HOA AP map."
    )


async def connect_varanus_ws(websockets, varanus_url, retries=20, delay_seconds=0.25):
    last_error = None
    for _ in range(retries):
        try:
            try:
                return await websockets.connect(
                    varanus_url,
                    compression=None,
                    ping_interval=None,
                )
            except TypeError:
                return await websockets.connect(varanus_url)
        except Exception as error:  # pragma: no cover
            last_error = error
            await asyncio.sleep(delay_seconds)
    raise RuntimeError(f"Could not connect to Varanus websocket at {varanus_url}: {last_error}")


async def gate_with_varanus(varanus_ws, raw_message):
    await varanus_ws.send(raw_message)
    reply_message = normalize_ws_message(await varanus_ws.recv())

    try:
        payload = json.loads(reply_message)
        if isinstance(payload, dict):
            return payload
        return {"verdict": "error", "raw_reply": payload}
    except json.JSONDecodeError:
        return {"verdict": "error", "raw_reply": reply_message}


def import_predictive_runtime_dependencies():
    try:
        import spot
        import websockets
        from predictive_ltl import PredictiveRuntime, Verdict
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "Missing Python dependency for monitor online/offline pipeline. "
            "Run monitor.py with a Python that has spot/buddy/websockets installed."
        ) from error

    return spot, websockets, PredictiveRuntime, Verdict


async def run_offline_pipeline(
    ltl_formula,
    projected_hoa_path,
    projection_map,
    trace_path,
    varanus_host,
    varanus_port,
):
    spot, websockets, PredictiveRuntime, Verdict = import_predictive_runtime_dependencies()

    runtime = PredictiveRuntime(ltl_formula, spot.automaton(projected_hoa_path))
    projected_symbols = set(projection_map.values())
    varanus_url = f"ws://{varanus_host}:{varanus_port}"

    start_time = time.time()
    processed_events = 0

    varanus_ws = await connect_varanus_ws(websockets, varanus_url)
    try:
        with open(trace_path, "r", encoding="utf-8") as source:
            for line_number, raw_line in enumerate(source, start=1):
                raw_event = raw_line.rstrip("\n")
                if raw_event == "":
                    continue

                processed_events += 1
                gate_reply = await gate_with_varanus(varanus_ws, raw_event)
                gate_verdict = str(gate_reply.get("verdict", "")).lower()
                log_pipeline(
                    "offline event #{idx}: raw='{raw}' varanus_verdict={verdict}".format(
                        idx=processed_events,
                        raw=raw_event,
                        verdict=gate_verdict,
                    )
                )

                if gate_verdict == "false":
                    elapsed = time.time() - start_time
                    print(f"RES: FALSE;source=varanus;line={line_number};events={processed_events};time={elapsed}")
                    return

                if gate_verdict != "currently_true":
                    continue

                parsed_event = gate_reply.get("parsed_event")
                if parsed_event is None:
                    continue

                projected_event = resolve_projected_event(
                    parsed_event,
                    projection_map,
                    projected_symbols,
                )

                predictive_verdict = runtime.step(projected_event)
                if predictive_verdict == Verdict.tt:
                    elapsed = time.time() - start_time
                    print(f"RES: TRUE;source=predictive;line={line_number};events={processed_events};time={elapsed}")
                    return
                if predictive_verdict == Verdict.ff:
                    elapsed = time.time() - start_time
                    print(f"RES: FALSE;source=predictive;line={line_number};events={processed_events};time={elapsed}")
                    return
    finally:
        await varanus_ws.close()

    elapsed = time.time() - start_time
    print(f"RES: ?;source=predictive;events={processed_events};time={elapsed}")


async def run_online_pipeline(
    ltl_formula,
    projected_hoa_path,
    projection_map,
    host,
    port,
    varanus_host,
    varanus_port,
):
    spot, websockets, PredictiveRuntime, Verdict = import_predictive_runtime_dependencies()
    projected_symbols = set(projection_map.values())
    varanus_url = f"ws://{varanus_host}:{varanus_port}"

    async def handler(client_ws, path=None):
        runtime = PredictiveRuntime(ltl_formula, spot.automaton(projected_hoa_path))
        log_pipeline("client connected: {addr}".format(addr=getattr(client_ws, "remote_address", None)))

        varanus_ws = await connect_varanus_ws(websockets, varanus_url)
        try:
            try:
                async for incoming in client_ws:
                    raw_message = normalize_ws_message(incoming)
                    if raw_message.strip() == "":
                        await client_ws.send(json.dumps({"status": "ignored", "reason": "empty message"}))
                        continue

                    try:
                        gate_reply = await gate_with_varanus(varanus_ws, raw_message)
                        gate_verdict = str(gate_reply.get("verdict", "")).lower()
                        log_pipeline(
                            "online event: raw='{raw}' varanus_verdict={verdict}".format(
                                raw=raw_message,
                                verdict=gate_verdict,
                            )
                        )

                        if gate_verdict != "currently_true":
                            response = {
                                "status": "blocked",
                                "verdict": gate_reply.get("verdict", "false"),
                                "decision_source": "varanus",
                                "reason": "varanus_rejected_or_ignored",
                                "varanus": gate_reply,
                            }
                            log_pipeline(
                                "decision source=varanus verdict={verdict}".format(
                                    verdict=response["verdict"]
                                )
                            )
                            await client_ws.send(json.dumps(response))
                            continue

                        parsed_event = gate_reply.get("parsed_event")
                        if parsed_event is None:
                            response = {
                                "status": "blocked",
                                "verdict": gate_reply.get("verdict", "false"),
                                "decision_source": "varanus",
                                "reason": "missing_parsed_event",
                                "varanus": gate_reply,
                            }
                            log_pipeline(
                                "decision source=varanus verdict={verdict} reason=missing_parsed_event".format(
                                    verdict=response["verdict"]
                                )
                            )
                            await client_ws.send(json.dumps(response))
                            continue

                        projected_event = resolve_projected_event(
                            parsed_event,
                            projection_map,
                            projected_symbols,
                        )
                        predictive_verdict = runtime.step(projected_event)

                        if predictive_verdict == Verdict.tt:
                            predictive_text = "true"
                        elif predictive_verdict == Verdict.ff:
                            predictive_text = "false"
                        else:
                            predictive_text = "?"

                        if predictive_text == "?":
                            final_verdict = "currently_true"
                            decision_source = "varanus"
                        else:
                            final_verdict = predictive_text
                            decision_source = "ltl"

                        log_pipeline(
                            "decision source={source} verdict={verdict} parsed='{parsed}' projected='{projected}' predictive={predictive}".format(
                                source=decision_source,
                                verdict=final_verdict,
                                parsed=parsed_event,
                                projected=projected_event,
                                predictive=predictive_text,
                            )
                        )

                        await client_ws.send(
                            json.dumps(
                                {
                                    "status": "ok",
                                    "verdict": final_verdict,
                                    "decision_source": decision_source,
                                    "varanus": gate_reply,
                                    "projected_event": projected_event,
                                    "predictive_verdict": predictive_text,
                                }
                            )
                        )
                    except Exception as error:
                        if is_websocket_closed_error(error):
                            break
                        try:
                            await client_ws.send(json.dumps({"status": "error", "error": str(error)}))
                        except Exception:
                            break
            except Exception as error:
                if not is_websocket_closed_error(error):
                    raise
        finally:
            await varanus_ws.close()
            log_pipeline("client disconnected: {addr}".format(addr=getattr(client_ws, "remote_address", None)))

    print(f"Online predictive monitor listening on ws://{host}:{port}")
    print(f"Varanus gate expected at ws://{varanus_host}:{varanus_port}")
    async with websockets.serve(handler, host, port):
        await asyncio.Future()


def main():
    parser = argparse.ArgumentParser(description="Monitor script for Varanus-first predictive LTL.")
    parser.add_argument("config", help="Path to the Varanus config.yaml file.", type=str)
    parser.add_argument("ltl", help="LTL formula to verify.", type=str)
    parser.add_argument("trace", nargs="?", help="Path to trace file (offline mode).", type=str)

    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument("--offline", action="store_true", help="Run offline mode with trace replay.")
    mode_group.add_argument("--online", action="store_true", help="Run online websocket mode.")

    parser.add_argument("--host", default="127.0.0.1", help="Predictive websocket host (online mode).")
    parser.add_argument("--port", type=int, default=5088, help="Predictive websocket port (online mode).")

    parser.add_argument("--varanus-script", default="varanus.py", help="Path to varanus.py.")
    parser.add_argument("--varanus-python", default="python3", help="Python executable for Varanus.")
    parser.add_argument("--varanus-host", default=DEFAULT_VARANUS_HOST, help="Varanus websocket host.")
    parser.add_argument("--varanus-port", type=int, default=DEFAULT_VARANUS_PORT, help="Varanus websocket port.")
    args = parser.parse_args()

    offline_mode = args.offline or not args.online

    if offline_mode and not args.trace:
        parser.error("trace is required in offline mode.")
    if args.online and args.port == args.varanus_port and args.host == args.varanus_host:
        parser.error("Predictive websocket host/port must differ from Varanus websocket host/port.")

    # 1) Build Varanus Buchi and project APs.
    run_varanus_buchi(args.config, args.varanus_script, args.varanus_python)

    generated_hoa = find_generated_hoa()
    try:
        projected_hoa, projection_map = project_hoa_file(
            input_hoa_path=generated_hoa,
            output_hoa_path="automaton_projected.hoa",
            mapping_output_path="event_projection_map.json",
            prefix="p",
        )
    except (FileNotFoundError, ValueError) as error:
        print(f"Error while projecting HOA: {error}")
        sys.exit(1)

    projected_ltl_formula = project_ltl_formula(args.ltl, projection_map)
    log_pipeline("ltl formula input: {f}".format(f=args.ltl))
    log_pipeline("ltl formula projected: {f}".format(f=projected_ltl_formula))

    # 2) Start Varanus online gate for both modes.
    varanus_process = start_varanus_online(args.config, args.varanus_script, args.varanus_python)
    print(
        "Standalone Varanus gate started "
        f"(pid={varanus_process.pid}) on ws://{args.varanus_host}:{args.varanus_port}"
    )

    try:
        if offline_mode:
            asyncio.run(
                run_offline_pipeline(
                    projected_ltl_formula,
                    projected_hoa,
                    projection_map,
                    args.trace,
                    args.varanus_host,
                    args.varanus_port,
                )
            )
        else:
            asyncio.run(
                run_online_pipeline(
                    projected_ltl_formula,
                    projected_hoa,
                    projection_map,
                    args.host,
                    args.port,
                    args.varanus_host,
                    args.varanus_port,
                )
            )
    except KeyboardInterrupt:
        print("Monitor stopped.")
    finally:
        stop_varanus_online(varanus_process)


if __name__ == "__main__":
    main()
